[build]
  command = "npm run build" # Команда для сборки вашего проекта
  publish = "Himchistka"          # Папка, куда помещаются собранные файлы

[dev]
  command = "npm run dev"    # Команда для запуска вашего приложения в режиме разработки
